--- # SensorBee plug-in list
Plugins:
- pfi/scouter-snippets/plugin
- pfi/scouter-snippets/plugin
- pfi/scouter-snippets/plugin
- pfi/scouter-snippets/plugin
#- pfi/sensorbee/scouter
#- pfi/sensorbee/fluentbee
